DEPLOY_REMOTE_HOST=ubuntu@52.67.135.170
DEPLOY_SSH_KEY=/home/daniel/Code/infra/amazon-infra/ec2/52.67.135.170/core/inatto01-sp.pem
DEPLOY_REMOTE_ROOT=/home/ubuntu/apps/bots/dev-automation/apps/amazon-imap-bot
DEPLOY_LOCAL_CONFIG_DIR=/home/daniel/Code/bots/dev-automation/.config/amazon-imap-bot
DEPLOY_REMOTE_CONFIG_DIR=/home/ubuntu/apps/bots/dev-automation/.config/amazon-imap-bot
