-- Amazon IMAP Bot - migração do catálogo antigo para estrutura relacional
-- Execução MANUAL. Idempotente. Oracle.
-- Execute este patch antes de 005_seed_function_catalog_relational.sql.
-- O patch remove as duas colunas JSON legadas de IMAP_BOT_FUNCTIONS.

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE WKSP_SINDICATTO.IMAP_BOT_FUNCTION_REASONING (
      function_name   VARCHAR2(100) NOT NULL,
      level_id        NUMBER(1) NOT NULL,
      enabled         CHAR(1) DEFAULT 'Y' NOT NULL,
      updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_IMAP_BOT_FUNC_REASON PRIMARY KEY (function_name, level_id),
      CONSTRAINT FK_IMAP_BOT_FR_FUNC FOREIGN KEY (function_name)
        REFERENCES WKSP_SINDICATTO.IMAP_BOT_FUNCTIONS(function_name),
      CONSTRAINT FK_IMAP_BOT_FR_LEVEL FOREIGN KEY (level_id)
        REFERENCES WKSP_SINDICATTO.IMAP_BOT_REASONING_LEVELS(level_id),
      CONSTRAINT CK_IMAP_BOT_FR_ENABLED CHECK (enabled IN ('Y','N'))
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE WKSP_SINDICATTO.IMAP_BOT_FUNCTION_PARAMETERS (
      function_name      VARCHAR2(100) NOT NULL,
      parameter_name     VARCHAR2(100) NOT NULL,
      data_type          VARCHAR2(20) NOT NULL,
      required           CHAR(1) DEFAULT 'N' NOT NULL,
      description        VARCHAR2(2000) NOT NULL,
      option_source      VARCHAR2(30) DEFAULT 'NONE' NOT NULL,
      sort_order         NUMBER(5) DEFAULT 0 NOT NULL,
      enabled            CHAR(1) DEFAULT 'Y' NOT NULL,
      updated_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_IMAP_BOT_FUNC_PARAM PRIMARY KEY (function_name, parameter_name),
      CONSTRAINT FK_IMAP_BOT_FP_FUNC FOREIGN KEY (function_name)
        REFERENCES WKSP_SINDICATTO.IMAP_BOT_FUNCTIONS(function_name),
      CONSTRAINT CK_IMAP_BOT_FP_TYPE CHECK (data_type IN ('string','integer','number','boolean')),
      CONSTRAINT CK_IMAP_BOT_FP_REQUIRED CHECK (required IN ('Y','N')),
      CONSTRAINT CK_IMAP_BOT_FP_OPT_SRC CHECK (option_source IN ('NONE','FUNCTION_REASONING_LEVELS','STATIC')),
      CONSTRAINT CK_IMAP_BOT_FP_ENABLED CHECK (enabled IN ('Y','N'))
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE WKSP_SINDICATTO.IMAP_BOT_FUNCTION_PARAM_OPTIONS (
      function_name    VARCHAR2(100) NOT NULL,
      parameter_name   VARCHAR2(100) NOT NULL,
      option_value     VARCHAR2(500) NOT NULL,
      sort_order       NUMBER(5) DEFAULT 0 NOT NULL,
      enabled          CHAR(1) DEFAULT 'Y' NOT NULL,
      updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_IMAP_BOT_FUNC_OPT PRIMARY KEY (function_name, parameter_name, option_value),
      CONSTRAINT FK_IMAP_BOT_FO_PARAM FOREIGN KEY (function_name, parameter_name)
        REFERENCES WKSP_SINDICATTO.IMAP_BOT_FUNCTION_PARAMETERS(function_name, parameter_name),
      CONSTRAINT CK_IMAP_BOT_FO_ENABLED CHECK (enabled IN ('Y','N'))
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM ALL_TAB_COLUMNS
   WHERE OWNER = 'WKSP_SINDICATTO'
     AND TABLE_NAME = 'IMAP_BOT_FUNCTIONS'
     AND COLUMN_NAME = 'ALLOWED_REASONING_LEVELS_JSON';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE WKSP_SINDICATTO.IMAP_BOT_FUNCTIONS DROP COLUMN ALLOWED_REASONING_LEVELS_JSON CASCADE CONSTRAINTS';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM ALL_TAB_COLUMNS
   WHERE OWNER = 'WKSP_SINDICATTO'
     AND TABLE_NAME = 'IMAP_BOT_FUNCTIONS'
     AND COLUMN_NAME = 'PARAMETERS_JSON';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE WKSP_SINDICATTO.IMAP_BOT_FUNCTIONS DROP COLUMN PARAMETERS_JSON CASCADE CONSTRAINTS';
  END IF;
END;
/
